// class ItemImage {
//   final String name;
//   final String path;
//   ItemImage({
//     required this.name,
//     required this.path,
//   });
// }

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ItemImage {
/*
{
  "name": "broccoli",
  "path": "assets/images/broccoli.png"
} 
*/

  String? name;
  String? path;

  ItemImage({
    this.name,
    this.path,
  });
  ItemImage.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    path = json["path"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["path"] = path;
    return data;
  }
}

class MyImage {
/*
{
  "Images": [
    {
      "name": "broccoli",
      "path": "assets/images/broccoli.png"
    }
  ]
} 
*/

  List<ItemImage?>? images;

  MyImage({
    this.images,
  });
  MyImage.fromJson(Map<String, dynamic> json) {
    if (json["Images"] != null) {
      final v = json["Images"];
      final arr0 = <ItemImage>[];
      v.forEach((v) {
        arr0.add(ItemImage.fromJson(v as Map<String, dynamic>));
      });
      images = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["Images"] = arr0;
    }
    return data;
  }
}
